### ISSUE TITLE
Error with generate_summary_bams.py

### ISSUE THREAD

**Issue by surendravikram** [kkdey/aRchaic#2]
Hi,

I am trying to run "generate_summary_bams.py" on the dataset other than human. I am getting the following error.

```
Traceback (most recent call last):
  File "/home/Softwares/aRchaic-master/bin/generate_summary_bams.py", line 71, in <module>
    for read in samfile.fetch(('chr' + str(chr)) if args.add_chr else str(chr)):
  File "pysam/libcalignmentfile.pyx", line 1066, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 675, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `1`
```

Thanks,

**Comment by halasadi** [comment]
Try adding the `--add-chr` option (`python generate_summary_bams.py --help` for more info) and let me know how that works.

**Comment by halasadi** [comment]
Actually, the script will not work with non-human data. We will add non-human data as a feature in the future. Or, you can modify the script.

Please modify these lines to suit your data.

`for chr in chrs:`

`for read in samfile.fetch(('chr' + str(chr)) if args.add_chr else str(chr)):`

**Comment by surendravikram** [comment]
Ok Thanks for the reply, I will try to modify the script.
