### ISSUE TITLE
Install fails due to due to missing export from Logolas

### ISSUE THREAD

**Issue by srcbs** [kkdey/aRchaic#3]
Dear Kushal and Hussein,

Im trying to install aRchaic and is getting the following error:

** preparing package for lazy loading
Error : object 'get_viewport_logo' is not exported by 'namespace:Logolas'
ERROR: lazy loading failed for package 'aRchaic'
* removing '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/aRchaic'

This happens both on my Linux server (CentOS) and on my Mac. I have already installed all dependencies - is this an issue with updates to Logolas not being reflected in aRchaic?

Best,

Simon

**Comment by kkdey** [comment]
Hi this is a problem with the fact that current version of Logolas works on the latest version of R, R 3.5.0.

As such however aRchaic should not try to install Logolas. Are you following the vignette here? https://kkdey.github.io/aRchaic/ and still see the error? can you please check if the error disappears if you update R to 3.5.0. Thanks.

**Comment by srcbs** [comment]
Thanks - it works with R-3.5, I was using R-3.4

Simon
